const MENU_DATA = [{
  "GNB": "",
  "LNB": "",
  "LAYOUT": "",
  "뎁스1": "상품",
  "뎁스2": "",
  "뎁스3": "",
  "PAGE": "",
  "진행 단계": "완료",
  "이슈": "",
  "기획": "",
  "디자인": "",
  "HREF": "",
  "child": [{
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "메인",
    "뎁스3": "",
    "PAGE": "products/main.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "상품/메인"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "리스트",
    "뎁스3": "",
    "PAGE": "products/list.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "상품/리스트"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "리스트 - 검색결과 없음",
    "뎁스3": "",
    "PAGE": "products/list_no_result.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "상품/리스트검색결과없음"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "리스트 - 브랜드",
    "뎁스3": "",
    "PAGE": "products/list2.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "상품/리스트브랜드"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "상세페이지",
    "뎁스3": "",
    "PAGE": "products/view.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "상품/상세페이지"
  }],
  "path": "상품"
}, {
  "GNB": true,
  "LNB": true,
  "LAYOUT": "basic",
  "뎁스1": "장바구니",
  "뎁스2": "",
  "뎁스3": "",
  "PAGE": "",
  "진행 단계": "완료",
  "이슈": "",
  "기획": "",
  "디자인": "",
  "HREF": "",
  "child": [{
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "장바구니",
    "뎁스3": "",
    "PAGE": "cart/cart.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "장바구니/장바구니"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "주문서 - 회원",
    "뎁스3": "",
    "PAGE": "cart/order.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "장바구니/주문서회원"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "주문서 - 비회원",
    "뎁스3": "",
    "PAGE": "cart/order_nomember.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "장바구니/주문서비회원"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "주문완료",
    "뎁스3": "",
    "PAGE": "cart/order_finish.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "장바구니/주문완료"
  }],
  "path": "장바구니"
}, {
  "GNB": true,
  "LNB": true,
  "LAYOUT": "basic",
  "뎁스1": "회원",
  "뎁스2": "",
  "뎁스3": "",
  "PAGE": "",
  "진행 단계": "완료",
  "이슈": "",
  "기획": "",
  "디자인": "",
  "HREF": "",
  "child": [{
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "가입",
    "뎁스3": "",
    "PAGE": "member/join.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "회원/가입"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "가입단계2",
    "뎁스3": "",
    "PAGE": "member/join2.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "회원/가입단계2"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "가입완료",
    "뎁스3": "",
    "PAGE": "member/join3.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "회원/가입완료"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "로그인",
    "뎁스3": "",
    "PAGE": "member/login.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "회원/로그인"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "아이디/비번 찾기",
    "뎁스3": "",
    "PAGE": "member/find-member.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "회원/아이디비번찾기"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "휴면회원 해제하기",
    "뎁스3": "",
    "PAGE": "member/member-certification.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "회원/휴면회원해제하기"
  }],
  "path": "회원"
}, {
  "GNB": true,
  "LNB": true,
  "LAYOUT": "basic",
  "뎁스1": "마이페이지",
  "뎁스2": "",
  "뎁스3": "",
  "PAGE": "",
  "진행 단계": "완료",
  "이슈": "",
  "기획": "",
  "디자인": "",
  "HREF": "",
  "child": [{
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "메인",
    "뎁스3": "",
    "PAGE": "mypage/mypage.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "마이페이지/메인"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "주문/배송내역",
    "뎁스3": "",
    "PAGE": "",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [{
      "GNB": true,
      "LNB": true,
      "LAYOUT": "basic",
      "뎁스1": "",
      "뎁스2": "",
      "뎁스3": "주문/배송내역",
      "PAGE": "mypage/order_catalog.html",
      "진행 단계": "",
      "이슈": "",
      "기획": "",
      "디자인": "",
      "HREF": "",
      "child": [],
      "path": "마이페이지/주문배송내역/주문배송내역"
    }, {
      "GNB": true,
      "LNB": true,
      "LAYOUT": "basic",
      "뎁스1": "",
      "뎁스2": "",
      "뎁스3": "주문상세 - 정상주문",
      "PAGE": "mypage/order_view.html",
      "진행 단계": "",
      "이슈": "",
      "기획": "",
      "디자인": "",
      "HREF": "",
      "child": [],
      "path": "마이페이지/주문배송내역/주문상세정상주문"
    }],
    "path": "마이페이지/주문배송내역"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "반품/교환내역",
    "뎁스3": "",
    "PAGE": "",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [{
      "GNB": true,
      "LNB": true,
      "LAYOUT": "basic",
      "뎁스1": "",
      "뎁스2": "",
      "뎁스3": "반품/교환내역",
      "PAGE": "mypage/return_catalog.html",
      "진행 단계": "",
      "이슈": "",
      "기획": "",
      "디자인": "",
      "HREF": "",
      "child": [],
      "path": "마이페이지/반품교환내역/반품교환내역"
    }, {
      "GNB": true,
      "LNB": true,
      "LAYOUT": "basic",
      "뎁스1": "",
      "뎁스2": "",
      "뎁스3": "주문상세 - 반품/교환주문",
      "PAGE": "mypage/return_view.html",
      "진행 단계": "",
      "이슈": "",
      "기획": "",
      "디자인": "",
      "HREF": "",
      "child": [],
      "path": "마이페이지/반품교환내역/주문상세반품교환주문"
    }, {
      "GNB": true,
      "LNB": true,
      "LAYOUT": "basic",
      "뎁스1": "",
      "뎁스2": "",
      "뎁스3": "반품 신청",
      "PAGE": "mypage/order_return.html",
      "진행 단계": "",
      "이슈": "",
      "기획": "",
      "디자인": "",
      "HREF": "",
      "child": [],
      "path": "마이페이지/반품교환내역/반품신청"
    }, {
      "GNB": true,
      "LNB": true,
      "LAYOUT": "basic",
      "뎁스1": "",
      "뎁스2": "",
      "뎁스3": "교환신청",
      "PAGE": "mypage/order_exchange.html",
      "진행 단계": "",
      "이슈": "",
      "기획": "",
      "디자인": "",
      "HREF": "",
      "child": [],
      "path": "마이페이지/반품교환내역/교환신청"
    }],
    "path": "마이페이지/반품교환내역"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "취소/환불내역",
    "뎁스3": "",
    "PAGE": "",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [{
      "GNB": true,
      "LNB": true,
      "LAYOUT": "basic",
      "뎁스1": "",
      "뎁스2": "",
      "뎁스3": "취소/환불내역",
      "PAGE": "mypage/refund_catalog.html",
      "진행 단계": "",
      "이슈": "",
      "기획": "",
      "디자인": "",
      "HREF": "",
      "child": [],
      "path": "마이페이지/취소환불내역/취소환불내역"
    }, {
      "GNB": true,
      "LNB": true,
      "LAYOUT": "basic",
      "뎁스1": "",
      "뎁스2": "",
      "뎁스3": "주문상세 - 취소/환불주문",
      "PAGE": "mypage/refund_view.html",
      "진행 단계": "",
      "이슈": "",
      "기획": "",
      "디자인": "",
      "HREF": "",
      "child": [],
      "path": "마이페이지/취소환불내역/주문상세취소환불주문"
    }],
    "path": "마이페이지/취소환불내역"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "위시리스트",
    "뎁스3": "",
    "PAGE": "mypage/wish.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "마이페이지/위시리스트"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "마이디자이너",
    "뎁스3": "",
    "PAGE": "mypage/mydesigner.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "마이페이지/마이디자이너"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "최근 본 상품",
    "뎁스3": "",
    "PAGE": "mypage/recently.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "마이페이지/최근본상품"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "배송지 관리",
    "뎁스3": "",
    "PAGE": "mypage/delivery_address.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "마이페이지/배송지관리"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "세금계산서",
    "뎁스3": "",
    "PAGE": "mypage/taxinvoice.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "마이페이지/세금계산서"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "개인결제",
    "뎁스3": "",
    "PAGE": "mypage/personal.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "마이페이지/개인결제"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "포인트 내역",
    "뎁스3": "",
    "PAGE": "mypage/emoney.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "마이페이지/포인트내역"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "쿠폰 내역",
    "뎁스3": "",
    "PAGE": "",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [{
      "GNB": true,
      "LNB": true,
      "LAYOUT": "basic",
      "뎁스1": "",
      "뎁스2": "",
      "뎁스3": "쿠폰 내역",
      "PAGE": "mypage/coupon.html",
      "진행 단계": "",
      "이슈": "",
      "기획": "",
      "디자인": "",
      "HREF": "",
      "child": [],
      "path": "마이페이지/쿠폰내역/쿠폰내역"
    }, {
      "GNB": true,
      "LNB": true,
      "LAYOUT": "basic",
      "뎁스1": "",
      "뎁스2": "",
      "뎁스3": "쿠폰 등록",
      "PAGE": "mypage/offlinecoupon.html",
      "진행 단계": "",
      "이슈": "",
      "기획": "",
      "디자인": "",
      "HREF": "",
      "child": [],
      "path": "마이페이지/쿠폰내역/쿠폰등록"
    }],
    "path": "마이페이지/쿠폰내역"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "1:1 문의 상세보기",
    "뎁스3": "",
    "PAGE": "mypage/myqna_view.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "마이페이지/11문의상세보기"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "1:1 문의 리스트",
    "뎁스3": "",
    "PAGE": "mypage/myqna_catalog.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "마이페이지/11문의리스트"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "1:1 문의 쓰기",
    "뎁스3": "",
    "PAGE": "mypage/myqna_write.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "마이페이지/11문의쓰기"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "상품Q&A 내역",
    "뎁스3": "",
    "PAGE": "mypage/mygdqna_catalog.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "마이페이지/상품QA내역"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "상품 리뷰",
    "뎁스3": "",
    "PAGE": "mypage/mygdreview_catalog.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "마이페이지/상품리뷰"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "회원정보 수정",
    "뎁스3": "",
    "PAGE": "",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [{
      "GNB": true,
      "LNB": true,
      "LAYOUT": "basic",
      "뎁스1": "",
      "뎁스2": "",
      "뎁스3": "비밀번호 확인",
      "PAGE": "mypage/myinfo.html",
      "진행 단계": "",
      "이슈": "",
      "기획": "",
      "디자인": "",
      "HREF": "",
      "child": [],
      "path": "마이페이지/회원정보수정/비밀번호확인"
    }, {
      "GNB": true,
      "LNB": true,
      "LAYOUT": "basic",
      "뎁스1": "",
      "뎁스2": "",
      "뎁스3": "회원정보 관리",
      "PAGE": "mypage/myinfo2.html",
      "진행 단계": "",
      "이슈": "",
      "기획": "",
      "디자인": "",
      "HREF": "",
      "child": [],
      "path": "마이페이지/회원정보수정/회원정보관리"
    }],
    "path": "마이페이지/회원정보수정"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "회원탈퇴",
    "뎁스3": "",
    "PAGE": "mypage/withdrawal.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "마이페이지/회원탈퇴"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "등급혜택",
    "뎁스3": "",
    "PAGE": "mypage/gradebenefit.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "마이페이지/등급혜택"
  }],
  "path": "마이페이지"
}, {
  "GNB": true,
  "LNB": true,
  "LAYOUT": "basic",
  "뎁스1": "게시판",
  "뎁스2": "",
  "뎁스3": "",
  "PAGE": "",
  "진행 단계": "완료",
  "이슈": "",
  "기획": "",
  "디자인": "",
  "HREF": "",
  "child": [{
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "FAQ",
    "뎁스3": "",
    "PAGE": "board/faq.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "게시판/FAQ"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "공지사항",
    "뎁스3": "",
    "PAGE": "",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [{
      "GNB": true,
      "LNB": true,
      "LAYOUT": "basic",
      "뎁스1": "",
      "뎁스2": "",
      "뎁스3": "공지사항",
      "PAGE": "board/notice.html",
      "진행 단계": "",
      "이슈": "",
      "기획": "",
      "디자인": "",
      "HREF": "",
      "child": [],
      "path": "게시판/공지사항/공지사항"
    }, {
      "GNB": true,
      "LNB": true,
      "LAYOUT": "basic",
      "뎁스1": "",
      "뎁스2": "",
      "뎁스3": "공지사항 상세보기",
      "PAGE": "board/notice_view.html",
      "진행 단계": "",
      "이슈": "",
      "기획": "",
      "디자인": "",
      "HREF": "",
      "child": [],
      "path": "게시판/공지사항/공지사항상세보기"
    }],
    "path": "게시판/공지사항"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "상품후기 리스트",
    "뎁스3": "",
    "PAGE": "board/goods_review.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "게시판/상품후기리스트"
  }],
  "path": "게시판"
}, {
  "GNB": true,
  "LNB": true,
  "LAYOUT": "basic",
  "뎁스1": "프로모션",
  "뎁스2": "",
  "뎁스3": "",
  "PAGE": "",
  "진행 단계": "완료",
  "이슈": "",
  "기획": "",
  "디자인": "",
  "HREF": "",
  "child": [{
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "이벤트 리스트",
    "뎁스3": "",
    "PAGE": "promotion/event.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "프로모션/이벤트리스트"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "이벤트 상세페이지",
    "뎁스3": "",
    "PAGE": "promotion/event-view.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "프로모션/이벤트상세페이지"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "애트니 라이브 - 리스트",
    "뎁스3": "",
    "PAGE": "promotion/atny_tv.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "프로모션/애트니라이브리스트"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "애트니 정책 안내",
    "뎁스3": "",
    "PAGE": "promotion/enjoy_atny.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "프로모션/애트니정책안내"
  }],
  "path": "프로모션"
}, {
  "GNB": true,
  "LNB": true,
  "LAYOUT": "basic",
  "뎁스1": "기타",
  "뎁스2": "",
  "뎁스3": "",
  "PAGE": "",
  "진행 단계": "완료",
  "이슈": "",
  "기획": "",
  "디자인": "",
  "HREF": "",
  "child": [{
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "디자이너",
    "뎁스3": "",
    "PAGE": "member/best-designers.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "기타/디자이너"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "기획전 상세페이지",
    "뎁스3": "",
    "PAGE": "member/event2.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "기타/기획전상세페이지"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "매거진 리스트",
    "뎁스3": "",
    "PAGE": "member/magazine-list.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "기타/매거진리스트"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "매거진 상세페이지",
    "뎁스3": "",
    "PAGE": "member/magazine-view.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "기타/매거진상세페이지"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "이용약관",
    "뎁스3": "",
    "PAGE": "service/agreement.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "기타/이용약관"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "개인정보처리방침",
    "뎁스3": "",
    "PAGE": "service/privacy.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "기타/개인정보처리방침"
  }, {
    "GNB": true,
    "LNB": true,
    "LAYOUT": "basic",
    "뎁스1": "",
    "뎁스2": "베스트아이템",
    "뎁스3": "",
    "PAGE": "products/best_seller.html",
    "진행 단계": "",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "기타/베스트아이템"
  }],
  "path": "기타"
}, {
  "GNB": "",
  "LNB": "",
  "LAYOUT": "",
  "뎁스1": "Markup reference",
  "뎁스2": "",
  "뎁스3": "",
  "PAGE": "",
  "진행 단계": "완료",
  "이슈": "",
  "기획": "",
  "디자인": "",
  "HREF": "",
  "child": [{
    "GNB": false,
    "LNB": false,
    "LAYOUT": "empty",
    "뎁스1": "",
    "뎁스2": "사이트맵",
    "뎁스3": "",
    "PAGE": "markup/PageSitemap.html",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "Markupreference/사이트맵"
  }, {
    "GNB": false,
    "LNB": false,
    "LAYOUT": "empty",
    "뎁스1": "",
    "뎁스2": "템플릿",
    "뎁스3": "",
    "PAGE": "",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "Markupreference/템플릿"
  }, {
    "GNB": false,
    "LNB": false,
    "LAYOUT": "empty",
    "뎁스1": "",
    "뎁스2": "레이어팝업 모음",
    "뎁스3": "",
    "PAGE": "markup/PageLayer.html",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "Markupreference/레이어팝업모음"
  }],
  "path": "Markupreference"
}, {
  "GNB": "",
  "LNB": "",
  "LAYOUT": "",
  "뎁스1": "샘플링",
  "뎁스2": "",
  "뎁스3": "",
  "PAGE": "",
  "진행 단계": "완료",
  "이슈": "",
  "기획": "",
  "디자인": "",
  "HREF": "",
  "child": [{
    "GNB": false,
    "LNB": false,
    "LAYOUT": "empty",
    "뎁스1": "",
    "뎁스2": "Handlebarsjs",
    "뎁스3": "",
    "PAGE": "",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "샘플링/Handlebarsjs"
  }, {
    "GNB": false,
    "LNB": false,
    "LAYOUT": "empty",
    "뎁스1": "",
    "뎁스2": "swiperjs",
    "뎁스3": "",
    "PAGE": "",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "샘플링/swiperjs"
  }, {
    "GNB": false,
    "LNB": false,
    "LAYOUT": "empty",
    "뎁스1": "",
    "뎁스2": "axios",
    "뎁스3": "",
    "PAGE": "",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "샘플링/axios"
  }, {
    "GNB": false,
    "LNB": false,
    "LAYOUT": "empty",
    "뎁스1": "",
    "뎁스2": "Plyr",
    "뎁스3": "",
    "PAGE": "",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "샘플링/Plyr"
  }, {
    "GNB": false,
    "LNB": false,
    "LAYOUT": "empty",
    "뎁스1": "",
    "뎁스2": "fontawesome",
    "뎁스3": "",
    "PAGE": "",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "샘플링/fontawesome"
  }],
  "path": "샘플링"
}, {
  "GNB": "",
  "LNB": "",
  "LAYOUT": "",
  "뎁스1": "라이브러리",
  "뎁스2": "",
  "뎁스3": "",
  "PAGE": "",
  "진행 단계": "완료",
  "이슈": "",
  "기획": "",
  "디자인": "",
  "HREF": "",
  "child": [{
    "GNB": "",
    "LNB": "",
    "LAYOUT": "",
    "뎁스1": "",
    "뎁스2": "Tailwind",
    "뎁스3": "",
    "PAGE": "https://tailwindcss.com/",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "라이브러리/Tailwind"
  }, {
    "GNB": "",
    "LNB": "",
    "LAYOUT": "",
    "뎁스1": "",
    "뎁스2": "Handlebarsjs",
    "뎁스3": "",
    "PAGE": "https://handlebarsjs.com/",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "라이브러리/Handlebarsjs"
  }, {
    "GNB": "",
    "LNB": "",
    "LAYOUT": "",
    "뎁스1": "",
    "뎁스2": "axios",
    "뎁스3": "",
    "PAGE": "https://axios-http.com/kr/",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "라이브러리/axios"
  }, {
    "GNB": "",
    "LNB": "",
    "LAYOUT": "",
    "뎁스1": "",
    "뎁스2": "swiperjs",
    "뎁스3": "",
    "PAGE": "https://swiperjs.com/",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "라이브러리/swiperjs"
  }, {
    "GNB": "",
    "LNB": "",
    "LAYOUT": "",
    "뎁스1": "",
    "뎁스2": "Plyr",
    "뎁스3": "",
    "PAGE": "https://plyr.io/",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "라이브러리/Plyr"
  }, {
    "GNB": "",
    "LNB": "",
    "LAYOUT": "",
    "뎁스1": "",
    "뎁스2": "fontawesome",
    "뎁스3": "",
    "PAGE": "https://fontawesome.com/v6/search?o=r&m=free",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "라이브러리/fontawesome"
  }, {
    "GNB": "",
    "LNB": "",
    "LAYOUT": "",
    "뎁스1": "",
    "뎁스2": "ScrollMagic",
    "뎁스3": "",
    "PAGE": "https://scrollmagic.io/",
    "진행 단계": "완료",
    "이슈": "",
    "기획": "",
    "디자인": "",
    "HREF": "",
    "child": [],
    "path": "라이브러리/ScrollMagic"
  }],
  "path": "라이브러리"
}];